version: 0.1

phases:
  install:
    commands:
      - yum -y install git python36 python36-devel gcc aws-cli
      - pip-3.6 install -r requirements.txt
      - pip-3.6 install -r dev_requirements.txt
      - mkdir dist artifacts

  pre_build:
    commands:
      - python36 -m unittest discover tests

  build:
    commands:
      - pip-3.6 install -r requirements.txt -t dist
      - cp -r handlers.py src dist/
      - "aws cloudformation package --template-file .ci/service.yml --s3-prefix build --s3-bucket $S3_BUCKET --output-template-file artifacts/template.yml"


  post_build:
    commands:
      - echo "Listing artifacts..."
      - "ls -lR artifacts/"
      - echo "Listing dist..."
      - "ls -l dist/"

artifacts:
  type: zip
  discard-paths: yes
  files:
    - artifacts/**/*
